apiVersion: apps/v1
kind: Deployment
metadata: 
  name: httpd-frontend
  labels:
    type: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      type: front-end
  template:
    metadata:
      name: httpd-pod
      labels:
        app: httpd-pod
        type: front-end
      spec:
       containers:
         - name: httpd:2.4-container
           image: httpd:2.4-alpine