apiVersion: apps/v1
kind: Service
metadata:
  name: myapp-clusterip-service
  labels:
    app: myapp
    type: front-end
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: myapp
    type: front-end