apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    name: result-app-service
    app: demo-voting-app
    type: front-end
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 81
      nodePort: 30009
  selector:
    name: result-app-pod
    app: demo-voting-app